### ISSUE TITLE
the function  Play control eip

### ISSUE THREAD

**Issue by rh1nox** [rh0dev/expdev#2]
hello , rh0dev！
I read you blog which write about the leak.In the end of article,you say: we call the ActiveX plugin’s Play method inside JavaScript (#256). This executes call [EAX + 0x30] with EAX pointing to the ovewritten field containing the address of our ROP chain.But when I disassemble it in IDA,I can't find the play function.I have to try find string:play in the String Window.I have not find the instruction:call [EAX + 0x30] in the disassemble of search,on the contrary ,found it in the function SetSliderPosition. I don't find that two links,can you give me more detials,thank you very much!

**Comment by rh0dev** [comment]
Hi micyee,

"call [eax+0x30]" is at the address videoplayer.ocx+0x6643B (see line #255). Inside the disassembly window of ida you can press "g" and then enter the address you want to jump to. Enter the absolute address (which is 0x1006643B in my case, as the base of videoplayer.ocx is at 0x10000000) and ida takes you to the call instruction. Note that the functions names which ida uses do not have to correspond to the JavaScript function names. Hope this helps.

Rh0
